# Generated by Django 3.0.6 on 2020-05-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
