# Generated by Django 3.0.6 on 2020-05-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_usetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usetime',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='img',
            new_name='content_img',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='program_info',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='user_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='user_info',
            field=models.CharField(default=models.DateTimeField(auto_now_add=True), max_length=100),
        ),
    ]
